version: "3.5"
services:
        dexpy:
                build: ./dexpy/
                image: dexpy:latest
                environment:
                        - DEXCOM_SHARE_SERVER=eu
                        - DEXCOM_SHARE_USERNAME=dexcomusername
                        - DEXCOM_SHARE_PASSWORD=dexcompassword
                        - MQTT_SERVER=mqttservername
                        - MQTT_PORT=1883
                        - MQTT_SSL=
                        - MQTT_CLIENTID=dexpy
                        - MQTT_TOPIC=cgm/dexcom
                        - INFLUXDB_SERVER=
                        - INFLUXDB_PORT=
                        - INFLUXDB_SSL=
                        - INFLUXDB_USERNAME=
                        - INFLUXDB_PASSWORD=
                        - INFLUXDB_DATABASE=
                        - NIGHTSCOUT_URL=
                        - NIGHTSCOUT_SECRET=
                        - NIGHTSCOUT_TOKEN=
                        - LOG_LEVEL=ERROR
